config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'scenarios/index'
  end

  root 'pages#home'

  get 'unauthorized', to: "pages#unauthorized"

  devise_for :user, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users do
      collection do
        get 'invite'
        post "invite", to: "users#send_invites"
      end
    end

    resources :scenarios do
      collection do
        post 'ajax_save'
        get 'ajax_load'
      end
    end
  end

  resources :scenarios do
    collection do
      get 'update_progress'
    end
  end

  resources :scenario_sessions

  resources :messages do
    collection do
      get 'inbox'
      get 'outbox'
      get '/:id/reply' => 'messages#reply_new', as: :reply
      post '/:id/reply' => 'messages#reply_create'
    end
  end

end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :sender, :class_name => 'User'
  belongs_to :scenario_session

  # validates :content, presence: true

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    redirect_to inbox_messages_path
  end

  def inbox
    if current_user.role == "user"
      @messages = Message.where.not(sender_id: current_user).joins(:scenario_session).where(:scenario_sessions => { student_id: current_user } ).all
    else
      @messages = Message.where.not(sender_id: current_user).joins(:scenario_session).where(:scenario_sessions => { teacher_id: current_user } ).all
    end
  end

  def outbox
    @messages = Message.where(sender_id: current_user)
  end

  def show
    @message = Message.where(id: params[:id]).last
    $role = @message.role
  end

  def reply_new
    @message = Message.where(id: params[:id]).last
    @reply = Message.new
    $session_id = @message.scenario_session_id
  end

  def reply_create
    @reply = Message.new(message_params)
    @reply.scenario_session_id = $session_id
    @reply.role = $role
    @reply.send_at = Time.now.to_datetime
    @reply.sender = current_user

    @reply.save

    flash[:notice] = "Het bericht is verstuurd"
    redirect_to inbox_messages_path
  end

  def new
  end

  def create
    @message = Message.new(message_params)
    @message.sender = current_user
    @message.send_at = Time.now.to_datetime
    @message.scenario_session_id = 1

    if @message.save
      redirect_to @message
    end

  end

  private
    def message_params
      params.require(:message).permit(:content)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/inbox.html.slim
div class="row clearfix"
  div class="col-md-12"
    div class="btn-group new-message" role="group"
      = link_to "Nieuw bericht", new_message_path, {class: "btn btn-primary new-scenario-button"}
    h3 Vandaag
    table class="table table-striped"
      thead class="row-head"
        tr
          th Afzender
          th Bericht
          th Tijdstip
      tbody class="row-body"
        - @messages.each do |message|
          tr
            - if current_user.role == "user"
              td.name = message.role
            - else
              td.name = message.sender.fullname
            td.content = link_to message.content, message_path(message.id)
            / td.content = message.content
            td.date = message.send_at

app/views/messages/new.html.slim
h2 Nieuw bericht

= form_for @message, :url => messages_path(@message), method: :post do |f|

  / .field
  /   = f.label :scenario_session
  /   br
  /   = f.select(:scenario_session_id, options_for_select(@scenario_session_options))

  .field
    = f.label :role, "Rol"
    br
    = f.text_field :role, autofocus: true

  .field
    = f.label :content, "Inhoud"
    br
    = f.text_area :content, autofocus: false

  .actions
    button type="submit" Verstuur

app/views/messages/outbox.html.slim
div class="row clearfix"
  div class="col-md-12"
    div class="btn-group new-message" role="group"
      = link_to "Nieuw bericht", new_message_path, {class: "btn btn-primary new-scenario-button"}
    h3 Vandaag
    table class="table table-striped"
      thead class="row-head"
        tr
          th: input type="checkbox"
          th Ontvanger
          th Bericht
          th Tijdstip
      tbody class="row-body"
        - @messages.each do |message|
          tr
            td: input type="checkbox"
            - if current_user.role == "user"
              td.name = message.role
            - else
              td.name = message.sender.fullname
            td.content = message.content
            td.date = message.send_at

app/views/messages/reply.html.slim
div class="row clearfix"
  div class="col-md-12"
    = form_for @reply, :url => reply_messages_path(@reply), method: :post do |f|

      .field
        = f.label :content
        br
        = f.text_area(:content)

      .actions
        = f.submit "Verstuur", class: "btn btn-primary"

app/views/messages/reply_new.html.slim
div class="row clearfix"
  div class="col-md-12"
    = form_for @reply, :url => reply_messages_path(@message), method: :post do |f|

      .field
        = f.label :content
        br
        = f.text_area(:content)

      .actions
        = f.submit "Verstuur", class: "btn btn-primary"

app/views/messages/show.html.slim
div class="row clearfix"
  div class="col-md-12"
    p Afzender:
    = @message.role
    p Inhoud van bericht:
    = @message.content

  div class="col-md-12"
    div class="btn-group reply-message" role="group"
      = link_to "Reageren", reply_messages_path, {class: "btn btn-primary new-scenario-button"}
  - if current_user.role == "superadmin" || current_user.role == "admin"
    div class="col-md-12"
      div class="btn-group show-session" role="group"
        = link_to "Sessie", scenario_session_path(@message.scenario_session_id), {class: "btn btn-primary new-scenario-button"}