config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'scenarios/index'
  end

  root 'pages#home'

  get 'unauthorized', to: "pages#unauthorized"

  devise_for :user, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users do
      collection do
        get 'invite'
        post "invite", to: "users#send_invites"
      end
    end

    resources :scenarios do
      collection do
        post 'ajax_save'
        get 'ajax_load'
      end
    end
  end

  resources :scenarios do
    collection do
      get 'update_progress'
    end
  end

  resources :scenario_sessions

  resources :messages do
    collection do
      get 'inbox'
      get 'outbox'
      get '/:id/reply' => 'messages#reply_new', as: :reply
      post '/:id/reply' => 'messages#reply_create'
    end
  end

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base

  has_many :scenario_session

  def node(id = 0, obj = self)
    object = nil

    if obj == self
      obj = JSON.parse self.content
      obj = obj["scenario"]['briefing']
    end

    if id == 0
      return obj
    else
      obj['children'].each do |child|
        if child["id"] == id
          object = child
          break
        end

        if child['children'].present?
          object = self.node(id, child)
          if object.present?
            break
          end
        end
      end
    end

    return object
  end

end

app/controllers/admin/scenarios_controller.rb
class Admin::ScenariosController < ApplicationController
  before_action :authorize_admin

  def index
    @scenarios = Scenario.all
    @scenario_sessions = ScenarioSession.all
  end

  def new
    @scenario = Scenario.new
  end

  def edit
    @scenario = params[:id]
  end

  # def create
  #   @scenario = Scenario.new(scenario_params)
  #   if @scenario.save
  #     redirect_to @scenario
  #   end
  # end

  def ajax_save
    id = request.POST['id']
    json = request.POST['data']
    obj = JSON.parse json
    title = obj["title"]
    # obj["scenario"]['briefing']['content']
    if id == "null"
      @scenario = Scenario.new
    else
      @scenario = Scenario.where(id:id).last
    end

    @scenario.title = title
    @scenario.content = json

    if @scenario.save
      render :json => {status: "success", id: @scenario.id}
      # TODO: Redirect to scenario index
      # flash[:notice] = "Scenario is opgeslagen"
      # redirect_to admin_scenarios_path
    else
      render :json => {status: "fail"}
    end
  end

  def ajax_load
    id = request.GET['id']
    if @scenario = Scenario.where(id:id).last
      render :json => {status: "success", id: @scenario.id, data: @scenario.content}
    else
      render :json => {status: "not found"}
    end

  end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  def new
    @scenario = Scenario.new
  end

  def create
    @scenario = Scenario.new(scenario_params)
    if @scenario.save
      redirect_to @scenario
    end

  end

  private
    def scenario_params
      params.require(:scenario).permit(:roles, :time_budget, :money_budget, :title, :description, :content)
    end

end

app/helpers/admin/scenarios_helper.rb
module Admin::ScenariosHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/admin/scenarios/edit.html.slim
#scenario-builder-wrapper
  div class="row clearfix"
    div class="col-md-9"
      #scenario-builder data-load_id="#{@scenario}"
    div class="col-md-3 builder-sidebar"
      / Templates go here

/ Webcomponents Templates
template id="form-contact-template"
  h3 Contact bewerken
  form
    p
      label Contact
      select
        option selected="selected" disabled="disabled" Selecteer een contact
        option Rol
    p
      label Uren
      input type="text" placeholder="Aantal uur"
    p
      label Kosten
      input type="text" placeholder="Kosten in Euro"
    p
      label Standaard respons
      textarea placeholder="Vul hier de standaard respons in"
    span class="optional" &#42;optioneel
    p
      button type="submit" Opslaan

template id="form-add-choice"
  h3 Nieuwe keuze
  form
    p
      label Contact met
      br
      select id="select-roles"

    p
      label Standaard respons
      textarea id="standard-response" placeholder="Vul hier de standaard respons in"

    p
      button type="submit" class="add-choice" Toevoegen

template id="form-add-situation"
  h3 Nieuwe situatie
  form
    p
      label Bericht
      textarea id="standard-response" placeholder="Vul hier het bericht in"
    p
      button type="submit" class="add-situation" Toevoegen

template id="form-edit-scenario"
  h3 Scenario Wijzigen
  form
    .field
      label for="form-scenario-title" Scenario naam
      br
      input type="text" id="form-scenario-title"

    .field
      label for="form-scenario-briefing" Scenario briefing
      br
      textarea id="form-scenario-briefing"
      br
      br
  h3 Factoren

  p Deze factoren zijn optioneel.

  form
    .field
      label for="form-scenario-time-budget" Tijdsbudget
      br
      input type="text" id="form-scenario-time-budget" placeholder="Uur .."

    .field
      label for="form-scenario-money-budget" Geldbudget
      br
      input type="text" id="form-scenario-money-budget" placeholder="€ .."

  p
    button type="submit" class="btn btn-primary" id="form-scenario-save" Scenario opslaan

template id="form-edit-choice"
  h3 Keuze wijzigen
  form
    p
      label Contact met
      br
      select id="select-roles"

    / p
    /   label Uren
    /   input type="text" placeholder="Aantal uur"
    / p
    /   label Kosten
    /   input type="text" placeholder="Kosten in Euro"
    p
      label Standaard respons
      textarea id="standard-response" placeholder="Vul hier de standaard respons in"
    p
      button type="submit" class="edit-choice" Aanpassen

app/views/admin/scenarios/index.html.slim
div class="row clearfix"
  div class="col-md-12"
    div class="btn-group new-message" role="group"
      = link_to "Nieuw scenario", new_admin_scenario_path, {class: "btn btn-primary new-scenario-button"}
    div class="btn-group new-message" role="group"
      = link_to "Nieuw scenario sessie", new_scenario_session_path, {class: "btn btn-primary new-scenario-button"}
    h1 Scenario's
    table class="table table-striped"
      thead class="row-head"
        tr
          th Projectnaam
          th Beschrijving
          th Sorteer
      tbody class="row-body"
        - @scenarios.each do |scenario|
          tr
            td.title = link_to scenario.title, edit_admin_scenario_path(scenario.id)
            td.description = scenario.description
            td
    h1 Simulaties
    table class="table table-striped"
      thead class="row-head"
        tr
          th Projectnaam
          th Student
          th Start datum
          th Eind datum
      tbody class="row-body"
        - @scenario_sessions.each do |scenario_session|
          tr
            td.title = link_to scenario_session.scenario.title, scenario_session_path(scenario_session.id)
            td.student = scenario_session.student.fullname
            td.start = scenario_session.start_date
            td.end = scenario_session.end_date.present? ? ("#{scenario_session.end_date}") : ("N.V.T.")

app/views/admin/scenarios/new.html.slim
#scenario-briefing
  div class=""
    h2 Nieuw scenario

    form
      .field
        label for="form-scenario-title" Scenario naam
        br
        input type="text" id="form-scenario-title"

      .field
        label for="form-scenario-briefing" Scenario briefing
        br
        textarea id="form-scenario-briefing"
        br
        br
    h3 Factoren

    p Deze factoren zijn optioneel.

    form
      .field
        label for="form-scenario-time-budget" Tijdsbudget
        br
        input type="text" id="form-scenario-time-budget" placeholder="Uur .."

      .field
        label for="form-scenario-money-budget" Geldbudget
        br
        input type="text" id="form-scenario-money-budget" placeholder="€ .."

    form
      fieldset class="roles"
        legend class="roles" Rollen
        .insert-roles
        button type="button" class="btn btn-default add-role-button" Extra rol toevoegen

    template id="role-template"
      .role
        h4 Rol
        .field
            label for="form-scenario-role-name" Naam
            input type="text" class="form-control" id="form-scenario-role-name" placeholder="Naam"

        .form-group
                  label for="form-scenario-role-role" Rol
                  input type="text" class="form-control" id="form-scenario-role-role" placeholder="Rol"

        .form-group
                  label for="form-scenario-role-description" Beschrijving
                  textarea style="max-with: 260px;" id="form-scenario-role-description" placeholder="Beschrijving"

    p
      button type="submit" class="btn btn-primary" id="form-scenario-new" Volgende

#scenario-builder-wrapper
  div class="row clearfix"
    div class="col-md-9"
      #scenario-builder
    div class="col-md-3 builder-sidebar"
      / Templates go here

/ Webcomponents Templates
template id="form-contact-template"
  h3 Contact bewerken
  form
    p
      label Contact
      select
        option selected="selected" disabled="disabled" Selecteer een contact
        option Rol
    p
      label Uren
      input type="text" placeholder="Aantal uur"
    p
      label Kosten
      input type="text" placeholder="Kosten in Euro"
    p
      label Standaard respons
      textarea placeholder="Vul hier de standaard respons in"
    span class="optional" &#42;optioneel
    p
      button type="submit" Opslaan

template id="form-add-choice"
  h3 Nieuwe keuze
  form
    p
      label Contact met
      br
      select id="select-roles"

    p
      label Standaard respons
      textarea id="standard-response" placeholder="Vul hier de standaard respons in"

    p
      button type="submit" class="add-choice" Toevoegen

template id="form-add-situation"
  h3 Nieuwe situatie
  form
    p
      label Bericht
      textarea id="standard-response" placeholder="Vul hier het bericht in"
    p
      button type="submit" class="add-situation" Toevoegen

template id="form-edit-scenario"
  h3 Scenario Wijzigen
  form
    .field
      label for="form-scenario-title" Scenario naam
      br
      input type="text" id="form-edit-scenario-title"

    .field
      label for="form-scenario-briefing" Scenario briefing
      br
      textarea id="form-edit-scenario-briefing"
      br
      br
  h3 Factoren

  p Deze factoren zijn optioneel.

  form
    .field
      label for="form-scenario-time-budget" Tijdsbudget
      br
      input type="text" id="form-edit-scenario-time-budget" placeholder="Uur .."

    .field
      label for="form-scenario-money-budget" Geldbudget
      br
      input type="text" id="form-edit-scenario-money-budget" placeholder="€ .."

  p
    button type="submit" class="btn btn-primary" id="form-scenario-save" Scenario opslaan

template id="form-edit-choice"
  h3 Keuze wijzigen
  form
    p
      label Contact met
      br
      select id="select-roles"

    / p
    /   label Uren
    /   input type="text" placeholder="Aantal uur"
    / p
    /   label Kosten
    /   input type="text" placeholder="Kosten in Euro"
    p
      label Standaard respons
      textarea id="standard-response" placeholder="Vul hier de standaard respons in"
    p
      button type="submit" class="edit-choice" Aanpassen