config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'scenarios/index'
  end

  root 'pages#home'

  get 'unauthorized', to: "pages#unauthorized"

  devise_for :user, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users do
      collection do
        get 'invite'
        post "invite", to: "users#send_invites"
      end
    end

    resources :scenarios do
      collection do
        post 'ajax_save'
        get 'ajax_load'
      end
    end
  end

  resources :scenarios do
    collection do
      get 'update_progress'
    end
  end

  resources :scenario_sessions

  resources :messages do
    collection do
      get 'inbox'
      get 'outbox'
      get '/:id/reply' => 'messages#reply_new', as: :reply
      post '/:id/reply' => 'messages#reply_create'
    end
  end

end

app/models/scenario_session.rb
class ScenarioSession < ActiveRecord::Base

  belongs_to :scenario
  belongs_to :teacher, :class_name => 'User'
  belongs_to :student, :class_name => 'User'
  has_many :messages

end

app/controllers/scenario_sessions_controller.rb
class ScenarioSessionsController < ApplicationController

  def new
    @scenarios_options = Scenario.all.map{|s| [s.title, s.id]}
    @teachers_options = User.where(role: [1,2]).map{|to| [to.fullname, to.id]}
    @students_options = User.where(role: 0).map{|so| [so.fullname, so.id]}

    @scenario_session = ScenarioSession.new
  end

  def show
    @scenario_session = ScenarioSession.where(id: params[:id]).last
  end

  def create
    @scenario_session = ScenarioSession.new(scenario_session_params)
    @scenario_session.teacher = current_user
    if @scenario_session.save
      send_briefing(@scenario_session)
      receiver_name = User.where(id: @scenario_session.student_id).first.fullname
      flash[:notice] = "De briefing is verstuurd naar #{receiver_name}"
      redirect_to admin_scenarios_path
    end
  end

  def send_briefing(scenario_session)
    @briefing = Message.new
    scenario = Scenario.where(id: scenario_session.scenario_id).first
    obj = JSON.parse scenario.content
    @briefing.content = obj["scenario"]['briefing']['content']
    @briefing.sender_id = scenario_session.teacher_id
    @briefing.scenario_session_id = scenario_session.id
    @briefing.role = "Opdracht gever"
    @briefing.send_at = Time.now.to_datetime
    @briefing.save
    update_progress
  end

  def update_progress
    # TODO: Figure out what the current id is
    #       Set the progress to the id of the next element in the scenario
    scenario = Scenario.where(id: @scenario_session.scenario_id).first
    obj = JSON.parse scenario.content

    if @scenario_session.progress == 0
      @scenario_session.progress = 1
    else

    end


    # @scenario_session.progress = obj["scenario"]['']
    if @scenario_session.save
      send_situation(@scenario_session)
      receiver_name = User.where(id: @scenario_session.student_id).first.fullname
      flash[:notice] = "De nieuwe situatie is verstuurd naar #{receiver_name}"
      redirect_to inbox_messages_path
    end

  end

  def send_situation(scenario_session)
    # TODO: Figure out which situation has te be send

    @situation = Message.new
    scenario = Scenario.where(id: scenario_session.scenario_id).first
    obj = JSON.parse scenario.content
    # @situation.content = obj["scenario"]['']
    @situation.sender_id = scenario_session.teacher_id
    @situation.scenario_session_id = scenario_session.id
    @situation.role = ""
    @situation.send_at = Time.now.to_datetime
    @situation.save
  end

  private
    def scenario_session_params
      params.require(:scenario_session).permit(:scenario_id, :student_id, :teacher_id, :start_date)
    end

end

app/helpers/scenario_sessions_helper.rb
module ScenarioSessionsHelper
end

app/views/scenario_sessions/new.html.slim
h2 Scenario sessie aanmaken

= form_for @scenario_session, :url => scenario_sessions_path(@scenario_session), method: :post do |f|

  .field
    = f.label :scenario_id
    br
    = f.select(:scenario_id, options_for_select(@scenarios_options))

  .field
    = f.label :student_id
    br
    = f.select(:student_id, options_for_select(@students_options))

  / .field
  /   = f.label :teacher
  /   br
  /   = f.select(:teacher_id, options_for_select(@teachers_options))

  .field
    = f.label :start_date
    br
    = f.text_field :start_date, class: "datepicker"

  .actions
    = f.submit "Opslaan", class: "btn btn-primary"

app/views/scenario_sessions/show.html.slim
div class="row clearfix"
  div class="col-md-12"
    h2 Scenario: #{@scenario_session.scenario.title}
    h2 Student: #{@scenario_session.student.fullname}
    h2 Docent: #{@scenario_session.teacher.fullname}
    / div class="btn-group new-message" role="group"
    /   = link_to "Volgende stap", update_progress_scenarios_path, {class: "btn btn-primary new-scenario-button"}