config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'scenarios/index'
  end

  root 'pages#home'

  get 'unauthorized', to: "pages#unauthorized"

  devise_for :user, controllers: { registrations: 'registrations' }

  namespace :admin do
    resources :users do
      collection do
        get 'invite'
        post "invite", to: "users#send_invites"
      end
    end

    resources :scenarios do
      collection do
        post 'ajax_save'
        get 'ajax_load'
      end
    end
  end

  resources :scenarios do
    collection do
      get 'update_progress'
    end
  end

  resources :scenario_sessions

  resources :messages do
    collection do
      get 'inbox'
      get 'outbox'
      get '/:id/reply' => 'messages#reply_new', as: :reply
      post '/:id/reply' => 'messages#reply_create'
    end
  end

end

app/views/layouts/_sidebar.html.slim
  / Sidebar
  div id="sidebar-wrapper"
    ul class="sidebar-nav"
      - if current_user.role == "superadmin" || current_user.role == "admin"
        li = link_to "Scenario's", admin_scenarios_path
        li = link_to "Gebruikers", admin_users_path
      li = link_to "Inbox", inbox_messages_path
      li = link_to "Outbox", outbox_messages_path
      li class="spacer"
        hr
      li = link_to "Account", edit_user_registration_path
      li = link_to "Uitloggen", destroy_user_session_path, method: 'DELETE'
  / Header/top menu
  div class="row clearfix"
    div class="col-md-12 column"
      nav class="navbar navbar-default navbar-fixed-top"
        div class="navbar-header"
          <a href="#menu-toggle" class="menu-button" id="menu-toggle"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
          span class="header-title" iHuman

app/views/layouts/application.html.slim
doctype html
html
  head
    title iHuman
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  - if request.path == "/user/sign_in"
    body class="gradient"
      div id="wrapper" class=""
        nav
          - if request.path != "/user/sign_in"
            = render "layouts/sidebar.html.slim"

        - if notice.present?
          div class="alert alert-info"
            a href="#" class="close" data-dismiss="alert" &times;
            strong Melding: 
            = notice

        - if alert.present?
          div class="alert alert-danger"
            a href="#" class="close" data-dismiss="alert" &times;
            strong Fout: 
            = alert

        == yield

  - else
    body
      div id="wrapper" class=""
        nav
          - if request.path != "/user/sign_in"
            = render "layouts/sidebar.html.slim"

        - if notice.present?
          div class="alert alert-info"
            a href="#" class="close" data-dismiss="alert" &times;
            strong Melding: 
            = notice

        - if alert.present?
          div class="alert alert-danger"
            a href="#" class="close" data-dismiss="alert" &times;
            strong Fout: 
            = alert

        == yield